### ISSUE TITLE
Post backdate not showing proper date

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#18] opened 2018-06-24 13:46 UTC
This article should show 5/21, but it shows a date in June: https://www.stanforddaily.com/2018/05/21/op-ed-stanford-health-cares-commitment-to-patient-safety-quality-and-the-most-favorable-patient-outcomes/

**Comment by hesyifei** [comment] 2018-10-24 06:31
Reference: http://support.jegtheme.com/forums/topic/post-date/

> On the previous update, we’ve been changing the post date from publish date into post modified date instead.

The code provided in that post does fix the problem, though I'm not sure if it will cause any new problem as we are essentially making [`get_the_modified_date`](https://developer.wordpress.org/reference/functions/get_the_modified_date/) the same as [`get_the_date`](https://developer.wordpress.org/reference/functions/get_the_date/):

```
add_filter('get_the_modified_date', function( $the_time, $d, $post )
{
	return get_the_date($d, $post);
}, 10, 3);
```

**Comment by hesyifei** [comment] 2018-10-29 17:08
Duplicate of #37

**Closed by hesyifei** 2018-10-29 17:08 UTC
